package Common;

public enum Requests {
    newUsername,
    login,
    signup,
    getPosts,
    getMyPosts,
    addPost,
    getUsers,
    follow,
    getNumbers,
    getNum,
    getFollowers,
    unfollow,
    like,
    dislike,
    getPostFeatures,
    getLikes,
    repost,
    addComment,
    getComments,
    setProfile,
    changeProfile,
    getProfile,
    setInformation,
    getInformation,
    setForgetPassword,
    getForgetPassword,
    changePassword,
    deleteAccount,
    logout,
    block,
    unblock,
    mute,
    unMute
}
